### ISSUE TITLE
The plugin break the right click on canvas

### ISSUE THREAD

**Issue by MelodyDuplaix** [HoBeom/obsidian-mouse-navigation#1]
With the plugin activated, the right-click menus on the canvas don't appear. It's very annoying because a lot of options aren't accessible otherwise.

**Comment by Hobeom** [comment]
Thank you for bringing up this issue, Melody!

In the current version of the plugin, the right-click menu is designed to appear when the mouse button is released, not when it’s pressed. I’ve experienced similar behavior during development, and it seems that this functionality may not work properly when Obsidian is not in focus.

It’s important for the right-click gesture feature to remain functional even when Obsidian is not focused, and I’m keen to fix this as soon as possible. Your feedback is very helpful in identifying this issue.

I appreciate your patience and will work on resolving it. Thanks again for reporting!
