### ISSUE TITLE
Navigation works when the settings are open

### ISSUE THREAD

**Issue by ATaimasov** [HoBeom/obsidian-mouse-navigation#3]
Hello again! 
I've found a new problem, but no significant as the previous one (issue №2).

The problem is the following: 
When obsidian settings are open, navigation still works for tabs.

Maybe it would be better to make it possible to use navigation in settings? 
Or completely disable navigation when settings are open?

Thank you for your great plugin!  `╰(*°▽°*)╯` 

![problem](https://github.com/user-attachments/assets/f8b63412-a4b9-4136-a955-7edc4fa8db54)

**Comment by Hobeom** [comment]
Thank you for pointing out this issue!

I will review the situation and update the plugin to disable gesture functionality when the settings are open.

Your feedback is greatly appreciated! 😊

**Comment by Hobeom** [comment]
Thank you for reporting this issue!

This problem has been resolved in version 1.0.2. Could you please update to the latest version and test if the issue is now fixed?

Your feedback would be greatly appreciated to ensure everything works as expected!

**Comment by ATaimasov** [comment]
Thank you for your work!
Problem solved, but there is a new problem from this. 
The right click in the file manager is broken. It does not work (in any way at all)

**Comment by Hobeom** [comment]
Thank you for your feedback!

I encountered the same issue right after the update, but it seemed to resolve itself after restarting Obsidian and re-enabling the plugin. If this issue consistently recurs after updates, I will need to review the problem further.

I appreciate you taking the time to test and report back. Thank you!

**Comment by ATaimasov** [comment]
Yes, the problem did indeed resolve after a restart. Thank you!
